### ISSUE TITLE
Example gallery should be more complete

### ISSUE THREAD

**Issue by bmcfee** [pescadores/pescador#106]
We need to cook up examples for all the common use cases for muxing following #103 :

1. chain mux for validation sets
2. poissonmux with stream reuse deactivated for full epoch sweeps (training)
3. shufflemux for small datasets with everything in ram
4. shufflemux + poissonmux for dealing with class balance in hierarchical sampling
5. *please add more use cases*

**Comment by bmcfee** [comment]
WIP over at #114 , but a couple of thoughts here:

- [x] chainmux example is done, but maybe could be improved?
- poissonmux for epoch sweeps is a bad idea, unless you disable the "poisson" part.  The reason being that you need to wrap the mux in a cycler to get streaming behavior (otherwise it stops after epoch 1), and you need to know how many examples are generated in an epoch to know when to trigger validation.  If the number of examples is stochastic (ie poisson), then you can't know this number.  (I still personally think epoch sweeps for training is an antipattern, but I know people want to do it.)

**Comment by bmcfee** [comment]
Training epoch example is up in #114 ; I think that basically covers it?

**Comment by cjacoby** [comment]
I'll take a look later today. :) :+1:

**Comment by bmcfee** [comment]
Fixed by merging #114
