### ISSUE TITLE
Remove StreamActivator class

### ISSUE THREAD

**Issue by bmcfee** [pescadores/pescador#108]
We removed the stream activator logic from `mux` in #103, but forgot to do the same for general Streamers.  See the discussion thread in #103 for why this makes sense and how to do it.

**Comment by cjacoby** [comment]
(That's not exactly true. We just talked about it but you said not to do it
for that PR.)

**Comment by bmcfee** [comment]
> (That's not exactly true. We just talked about it but you said not to do it
> for that PR.)

Yeah, you're right.  Brain is going in my old age :rofl:.  But we should do it now / after merging #109

**Comment by cjacoby** [comment]
It is done
