### ISSUE TITLE
Make `Streamers`' `iterate()` return a copy of the streamer

### ISSUE THREAD

**Issue by cjacoby** [pescadores/pescador#112]
As identified in #111, when activated, each `Streamer` generator maintains the state of the original object. This is a bug in situations such as `PoissonMux(mode='with_replacement')`, where the stream can be used multiple times. (See discussion in #111 for more details).

Proposals for fixing:
* Have the context manager make a copy of the streamer to activate, which is then used instead of `self` within the context.

Questions / Clarifications:
* Is returning a shallow copy sufficient?
* Option for deep copy? (i.e. `deep=True/False`)
* Maybe provide an option in `.iterate()` to set whether a copy happens or not, for the following case identified by @bmcfee:
> ... I think it's fair to expect each streamer (reference) to behave independently. *Where this gets really nasty is when stacking muxen, which could have deep state to copy.*

**Comment by bmcfee** [comment]
> Is returning a shallow copy sufficient?

Nope: if the streamers are muxes, there's non-trivial state to propagate.  If they're muxes of muxes, a shallow copy would fail.

> Option for deep copy? (i.e. deep=True/False)

I'd prefer to limit options as much as possible.  These objects are generally lightweight, so a deepcopy shouldn't be too bad?

**Comment by bmcfee** [comment]
One thought though: returning a copy of the object as a context might play tricks with any callback / state logging we want to do #94 .  @ejhumphrey thoughts?

**Comment by cjacoby** [comment]
Fixed in #113.
