### ISSUE TITLE
k_active or n_active?

### ISSUE THREAD

**Issue by bmcfee** [pescadores/pescador#115]
Having played around with the refactored muxen, I'm wondering why the parameter in `PoissonMux` is `k_active` instead of `n_active`?  Is it too late to change?

**Comment by cjacoby** [comment]
Well, as far as I'm concerned, the story goes like this:

* It used to be called `k`
* @ejhumphrey requested it be changed to `k_active` to be clearer about
what `k` was.
* I did it.

I got no feelings here; I believe it was called `k` for "n choose k"
perspective, ya? But now that it has a different name than just `k`,
`n_active` might be clearer. I'm happy with that change if you are.

**Comment by bmcfee** [comment]
Thanks for the clarification -- i figured it was something like that.  I do think `n_active` would be clearer.  Any objection @ejhumphrey ?
