### ISSUE TITLE
max_iter vs cycle?

### ISSUE THREAD

**Issue by bmcfee** [pescadores/pescador#116]
In implementing the epoch example for #114, I noticed that `cycle` and `max_iter` don't play nicely together.  I guess this was always the case, and it makes sense: cycle should run indefinitely, but max_iter explicitly bounds the number of steps.

I think it's not unreasonable to expect
```python
streamer(cycle=True, max_iter=N)
```
to still generate `N` steps, and cycle internally if necessary to get there.

Is that behavior that we want to support?  The `RoundRobinMux` kind of does this in permuted mode, so it could be generalized.  OTOH, I'm fine with just saying that the two modes are incompatible and throwing an exception if `cycle and max_iter is not None`.

**Comment by cjacoby** [comment]
So, in this case, cycle would always mean "restart the streamer when it is exhausted", right?

I think we may have to be more careful about their implementation than the current, somewhat ad-hoc approach (cycle is just while True:, iterate()), but I do like the notion of generalizing this sort of behavior a little better.

**Comment by cjacoby** [comment]
(Also: Some mux (`ShuffledMux`, for instance) actually *always* cycle on this definition. )

**Comment by bmcfee** [comment]
> So, in this case, cycle would always mean "restart the streamer when it is exhausted", right?

Yeah.  The logic would basically thread the `max_iter` param down through the cycle function.  It would complicate the implementation a little, but not by much.  I think the semantics should be pretty clear: `cycle` means loop the whole thing, and regardless of cycling behavior, always stop after `max_iter` samples.
