### ISSUE TITLE
Proposal: PoissonMux -> StochasticMux

### ISSUE THREAD

**Issue by bmcfee** [pescadores/pescador#119]
@cjacoby Since 2.0 isn't yet final, what do you think about renaming the new `PoissonMux` class to a more generic `StochasticMux` class?  I know we discussed having this as an intermediate abstract class, but I'm thinking it makes more sense to make the rate sampling just a separate parameter rather than a derived class.

In setting up the experiments described in #104 , I got to thinking it would be worth trying out different rate samplers but keeping the rest of the poissonmux behavior fixed.  E.g., instead of poisson-distributed, we could have negative binomial, discrete uniform, etc.  This would be easy if we could 
construct a `StochasticMux(..., schedule='poisson')` or `StochasticMux(..., schedule='uniform')`, rather than having to derive a new class each time we want a new scheduler.

**Comment by bmcfee** [comment]
... for now though, I think I'm content to just rename the class and worry about adding scheduler params in the future.

**Comment by cjacoby** [comment]
I'm fine with that. It think (aside from the class rename), that would
ultimately be a pretty small change to that class, that would not
significantly affect the end-user (especially if you leave the default as
Poisson.

So yes, I'd say "rename" => 2.0
custom distribution => 2.later
