### ISSUE TITLE
Minimum version requirements on dependencies

### ISSUE THREAD

**Issue by bmcfee** [pescadores/pescador#121]
We need to sort this out in advance of 2.0.

**Comment by bmcfee** [comment]
PR forthcoming; quick log of notes after deep-diving changelogs:

- six
  - 1.2 iteritems, advance_iterator
  - 1.3 callable
  - 1.4 PY2 constant
  - 1.8 reraise

- pyzmq
  - 14.6: copy/deepcopy on contexts?
  - 16.0 to be safe

- numpy >= 1.9 for RandomState compat

- decorator >= 4.0

- numpydoc >= 0.6 for generator docs

- sphinx-gallery >= 0.1.10 (backwards incompat changes

- pytest-timeout >= 1.2 (float time)

**Comment by cjacoby** [comment]
I appreciate your thoroughness here 🥇
