### ISSUE TITLE
Put docs link in github header?

### ISSUE THREAD

**Issue by cjacoby** [pescadores/pescador#124]
Can we put the docs link in the github header? (http://pescador.readthedocs.io/)

I see this practice all over github ([for instance](https://github.com/pallets/flask)), and I really like it getting to the docs quickly. I'm pretty sure I have permissions to do this, but wanted to ask first.

**Comment by bmcfee** [comment]
I don't see a doc header on the flask repo?  We have a link to docs at the bottom, but I agree that a badge/header link would be better.

**Comment by cjacoby** [comment]
I think it's more the "subtitle" than "header", but I'm not sure exactly how github calls it.

Here:
![image](https://user-images.githubusercontent.com/929267/35525798-5ce88b48-04da-11e8-8395-4c3374d8ccda.png)

ie: `Stochastic multi-stream sampling for iterative learning https://pescador.readthedocs.io`

**Comment by bmcfee** [comment]
Ooooh, I thought you meant in the readme.  Sure, this is easy.
