### ISSUE TITLE
A `streamable` decorator?

### ISSUE THREAD

**Issue by ejhumphrey** [pescadores/pescador#129]
**disclaimer**: this is a pretty simple proposal for some syntactic sugar.

I dunno about anyone else, but I find myself writing `stream = pescador.Streamer(foo, ...)` all over the place, where `foo` is some generator function I only ever want to use in pescador, for example...

```python
def random_samples(input_shape, k_classes, seed=None):
    rng = np.random.RandomState(seed)
    while True:
        yield dict(x=rng.uniform(size=input_shape), 
                   y=rng.randint(0, k_classes))
streamers = [pescador.Streamer(random_samples, input_shape, k_classes) 
             for _ in range(10000)]
mux = pescador.mux.StochasticMux(streamers, n_active=100, rate=100)
batches = pescador.Streamer(pescador.buffer_stream, mux, 32)
tuples = pescador.Streamer(pescador.tuples, batches, 'x', 'y')
``` 

Does anyone have any thoughts on introducing a `streamable` decorator to clean some of this up?

```python 
def streamable(func):
    def streamed(*args, **kwargs):
        return pescador.Streamer(func, *args, **kwargs)
    return streamed

@streamable
def random_samples(input_shape, k_classes, seed=None):
    rng = np.random.RandomState(seed)
    while True:
        yield rng.uniform(size=input_shape)

@streamable
def times_two(iterable):
    for x in iterable:
        yield x * 2

streamers = [random_samples(input_shape, k_classes) for _ in range(10000)]
mux = pescador.mux.StochasticMux(streamers, n_active=100, rate=100)
stream = times_two(mux)

for sample in stream.iterate(max_iter=10):
    # do something...
```

thoughts? concerns?

**Comment by bmcfee** [comment]
I like the idea in principle.  Have you tried it?

**Comment by cjacoby** [comment]
I like :+1:

**Comment by ejhumphrey** [comment]
yea, i've been using it for the last couple days and i like it. I just copy-pasted out what i've been using above.

the *only* issue I think I've seen so far is that `Streamer`s aren't 100% interchangeable for generators (iirc) ... I've seen some things hiccup here and there, but didn't take notes and can't give an example. Adding a decorator can make it hard from context to determine the object type (generator vs Streamer) in separate code.

If I've got the right of this (which is definitely an if, I'm like 65% confident), then this might warrant a little bit more work to bring streamers just a little bit closer to generators. Y'all have any ideas on this?

**Comment by bmcfee** [comment]
I like this pattern a lot.  I don't understand what the issue is with distinguishing streamers from generators though?  I guess what you lose is direct access to the underlying function (the generator), but you can always access that by saying, eg,
```python
random_samples.streamer
```
I don't know why you would need to do that, but I guess you have reasons?
