### ISSUE TITLE
Drop python 2 support

### ISSUE THREAD

**Issue by bmcfee** [pescadores/pescador#149]
We really should stop trying to support python 2.  All the frameworks are now up to speed with python 3, and it will allow us to remove a good amount of shim code to keep legacy installs working.

Minimum python version should bump to at least 3.5, if not 3.6.  If we go to 3.6, we can have asynchronous generators (#30).

**Comment by cjacoby** [comment]
My emotional vote would be 3.6, but I guess 3.5 would be more friendly.

**Comment by bmcfee** [comment]
I actually think async generators are a strong enough reason to bypass 3.5.  It's a feature we eventually want anyway, so hanging on to 3.5 support is really just adding more work for us down the road.  The [2018 survey](https://www.jetbrains.com/research/python-developers-survey-2018/) has 3.5 at 11% adoption, and >=3.6 at 84%, so I don't realistically think we'd be losing too many users.  (Migrating from 3.5 to 3.6 is relatively easy anyway.)

**Comment by cjacoby** [comment]
I'm sold :+1:

That is an awesome survey/writeup thanks for sharing :)

**Comment by hugovk** [comment]
Please see PR https://github.com/pescadores/pescador/pull/155.

**Comment by bmcfee** [comment]
fixed by #166
