### ISSUE TITLE
Buffer Streamer as a subclass of Streamer

### ISSUE THREAD

**Issue by cjacoby** [pescadores/pescador#31]
Proposed refactor / feature / update / future release:
* Turn the `buffer_streamer` function into a `BufferStreamer` class, as a subclass of `pescador.Streamer`. It's `generate()` function would then yield batches of `batch_size`.
* Optionally: `ZMQStreamer` also being a subclass of `pescador.Streamer`

This makes a lot of intuitive sense to me, and would allow introspection of a sort on the "Buffer Streamer". Under OO semantics, I think that `BufferStreamer` logically "is a" `Streamer`, and `ZMQStreamer` also "is a" `Streamer`.

Thoughts / reasons not to do this? (other than time/effort; I can probably help with that, although  maybe not until I've finished a couple of other things).

**Comment by bmcfee** [comment]
I think you're right.

If I had to take a stab at explaining why `zmq_streamer` and `buffer_streamer` are functions and not classes, it's that I wanted to keep `Streamer` dead simple, and use `has-a` semantics on buffering and IPC, rather than `is-a`.  This way, you could decouple the streamer construction from how it gets passed around and ultimately consumed.

I suppose you could always stick an upcast/`from_streamer` class method on the derived classes for the same effect.

I like promoting `ZMQStreamer` to a class -- it would make it possible to easily restart IPC streamers, say, across iterations of a cross-validation loop.

**Comment by bmcfee** [comment]
While we're at it: what do you think about promoting `mux` into a streamer?

Its pattern is different from the others, but it still exposes the same consumption/`generate` interface.

**Comment by cjacoby** [comment]
I was thinking about it, but I hadn't made up my mind on that yet, so I didn't mention it above.

My current thinking is that a "Streamer" minimally:
* consumes another generator(s?) of some kind.
* has a `generate()` function to expose that generator
* Maybe has a `next()` and/or `__iter__()` which wraps the `generate()` in a nice way.

I think by that definition, then a mux is just a streamer that takes multiple streamers as input, so I would agree, but then results in a streamer. (This would actually make it so you don't need to often wrap a mux in a streamer, which would be nice.)

**Comment by bmcfee** [comment]
> This would actually make it so you don't need to often wrap a mux in a streamer, which would be nice.

Exactly.


> has a generate() function to expose that generator

For the purposes of an API, this is all that really matters.


> Maybe has a next() and/or __iter__() which wraps the generate() in a nice way.

I'm not sure that can be done.  I originally wanted to work that way, but it's really strange when it comes to restarting.  Wrapping `generate` in a loop doesn't quite work because it won't continue after the `StopIteration` is thrown.  Maybe there's a clever way to handle this silently?

**Comment by cjacoby** [comment]
Ah, I see why that would be a problem. For me, a common use case with pescador is training my NNs essentially infinitely on all my streams, in which case I always basically want to use it like this:

```
for batch in streamer.generate():
   ...
```

Right now it is confusing that the API is not the same across all the pieces; I just want that not to be the case. But it also feels natural in the case that I'm describing to use it like this:

```
for batch in streamer:
   # do this till i cancel it (early stopping, manually, whatever)
```

But maybe a helper function of some kind would be better, since maybe `Streamer`s should be defined not to be able to have `__iter__`s for your stated reasoning.

```
for batch in streamer.infinite():
   # do this till i cancel it (early stopping, manually, whatever)
```

... or something like that.

**Comment by bmcfee** [comment]
Yeah, I agree that it would be best if streamers could operate transparently as iterables.

Maybe we can just maintain generator state with an variable?  Something like:

```python
class Streamer(object):
    ....
    def __init__(self, streamer, *args, **kwargs):
        ...
        self.stream_ = None

    def __iter__(self):
        if self.stream_ is None:
            self.stream_ = self.streamer(*self.args, **self.kwargs)
        try:
            yield from self.stream_
        except StopIteration as exc:
            six.reraise(exc)
        finally:
            self.stream_ = None
```
(and python2 compatibility, count limiting, etc.)

I haven't tried this, but I think it would allow the following to work:
```python
>>> streamer = Streamer(my_generator, arg1, arg2, ...)
>>> [batch for batch in streamer]
>>> [batch for batch in streamer]
>>> [batch for batch in streamer]
...
```

My concern here is that the object may become impossible to serialize, which would make `zmq_streamer` a real headache when moving streamers across the process boundary.  Maybe we could catch the serialization on the fly by implementing `__reduce__`, and replace `stream_=None` before serializing?  This would interrupt any streams in progress, but I'm okay with that.

**Comment by bmcfee** [comment]
I tried this out and it basically works.  `finally` is the wrong way to do that, as it prevents the iterator from persisting if interrupted without exhaustion.

This works:

```python
class Streamer(object):
    def __init__(self, streamer, *args, **kwargs):
        self.streamer = streamer
        self.args = args
        self.kwargs = kwargs
        self.stream_ = None

    def __iter__(self):
        if self.stream_ is None:
            self.stream_ = self.streamer(*self.args, **self.kwargs)
        try:
            yield from self.stream_
        except StopIteration as exc:
            self.stream_ = None
            six.reraise(exc)
            
        self.stream_ = None
    
    def __reduce__(self):
        self.stream_ = None
        return super(Streamer, self).__reduce__()
```

Probably this can be cleaned up to use the right `collections.abc` type for multi-pass iterators, but as a first cut it ought to work.

**Comment by bmcfee** [comment]
Digging deeper, I came across this line in the [collections docs](https://docs.python.org/3/library/stdtypes.html#typeiter):

> Once an iterator’s `__next__()` method raises `StopIteration`, it must continue to do so on subsequent calls. Implementations that do not obey this property are deemed broken.

So maybe we just shouldn't do this?  Alternately, we could make infinite/repeat-streaming an object property, or a separate class.

**Comment by bmcfee** [comment]
> Alternately, we could make infinite/repeat-streaming an object property, or a separate class.

Derp, the problem with this is that mux will need to be able to force infinite streams.  I don't think `itertools.cycle` is quite correct for this either.  Perhaps we just need to do as you say and implement a separate generator function `Streamer.cycle()`.

**Comment by cjacoby** [comment]
+1 on keeping pythonic things pythonic in expected ways, and having different semantics for different behaviors.

**Comment by bmcfee** [comment]
Ok.  In that case: is this fleshed out conceptually enough to start hacking on friday?

**Comment by cjacoby** [comment]
Yes, I think so. Do you prefer this over #30? I think this might be a prerequisite for #30, actually.

**Comment by cjacoby** [comment]
Proposal / summary (how I'm thinking about this after trying to do it once):

- A parent `Streamer` class/mixin which consumes only a `Streamer` or `generator`/`iterable`.
  - `generate(max_batches)` method iterates until `StopIteration`, and then stops.
  - `cycle()` method forces iterating infinitely

- `BufferStreamer(Streamer)` class consumes a streamer or generator/iterable, and converts `generate()` to returning batches of size (n)

- `FunctionStreamer(Streamer)` class consumes a function and `*args`/`**kwargs`. Open to ideas for better names.

- `MuxStreamer(Streamer)` class consumes a list (as `*args`) of `Streamer`s or generator/iterables, and `**kwargs` containing the parameters for controlling the streams.

- `ZMQStreamer(Streamer)` consumes a streamer or generator/iterable, and does the zmq thing, as in `zmq_stream`

Thoughts / confirmation?

**Comment by bmcfee** [comment]
I think #34 resolves this one, correct?

**Comment by bmcfee** [comment]
pinging @cjacoby : does #34 resolve this?

**Comment by bmcfee** [comment]
Cool.  Is there anything else that we wanted to do on the dev/0.2 branch?

**Comment by cjacoby** [comment]
List off the top of my head:

* Doc/example updates for new API
* Possibly backwards function compatible wrappers with deprecation warnings?

Probably anything else could be a future release.
