### ISSUE TITLE
canonical examples

### ISSUE THREAD

**Issue by ejhumphrey** [pescadores/pescador#40]
Based on my experience / sufferings, I think it'd be nice to have some canonical examples of The Right Ways to use pescador as benchmarkable scripts (timings and throughput). A few come to mind...

- [x] reading from NPZ files
- [x] data augmentation
- [x] parallelism (updated)

any others?

**Comment by cjacoby** [comment]
:+1:

We could make another repo in the pescadores/ with examples, or something
like that.

Some of those things may end up being so common as to want some kind of
wrapper library? I've found this to be true, in practice.

**Comment by bmcfee** [comment]
Implemented as #47
