### ISSUE TITLE
Leaky Numpy (NPZ) Gotchas

### ISSUE THREAD

**Issue by ejhumphrey** [pescadores/pescador#41]
First off, this is not strictly a pescador issue / bug. **However**, given the normal use cases of pescador, I do think this has the potential to be a common trap, and is worth documenting for posterity (especially here, which is where I assume future inquiries might land first). 

As I've tried to explore and document in [this repository](https://github.com/ejhumphrey/pescador-wtf), there are **two** things one must do to avoid memory leaks when pulling data from numpy's archive files ('.npz').

- Use a ContextManager when accessing the file, e.g. `with np.load(npz_file) as data: ...`
- Do not yield references to ndarrays via `dict`s; arrays created in the yield statement are kosher  e.g. `yield dict(x=np.array(x[n:n+k]))`

Both of these points make perfect sense in hindsight, though neither were particularly obvious to me at first. Am I alone in my oversight? What's the best way to document this?

### Appendix:
For clarity, a safe NPZ archive sampler looks like the following:
```
import numpy as np

def npz_sampler(npz_file):
    """Randomly sample aligned rows from an NPZ archive"""
    with np.load(npz_file) as data:
        x, y = data['x'], data['y']

    while True:
        i = np.random.randint(len(x))
        yield dict(x=np.array(x[i:i + 1]), y=np.array(y[i:i + 1]))
```

**Comment by ejhumphrey** [comment]
aaand way too many hours later, @cjacoby I think you'll be most interested in this.

**Comment by cjacoby** [comment]
I'm not sure I follow the second bullet; can you provide an example of what *not* to do?

I am probably doing all of these things, so I am extremely grateful for the pointers.

IMO there should be a separate pescadores repo (I've said this elsewhere / I have the beginnings of this already) with helper functions for extremely common things like this.

**Comment by ejhumphrey** [comment]
both of these are bad:

```
def leaky_sampler_a(filename):
    with np.load(filename) as data:
        x = data['x']

    while True:
        i = np.random.randint(len(x))
        yield dict(x=x[i:i + 1])


def leaky_sampler_b(filename):
    x = np.array(np.load(filename)['x'])
    while True:
        i = np.random.randint(len(x))
        yield dict(x=x[i:i + 1])
```
you see what's going on? 

IIUC, the slice operation returns a reference to the allocated array from whence it came. And so, when that identifier gets socked into a dictionary, that dictionary is the new owner of the reference to _original array_ that was created in the generator. But, the ndarray's reference is now hidden behind the dict, thus muddying the waters as to when the array has gone out of scope, e.g. killing the generator doesn't dereference the array it created.

makes for a neat python test question...

Also, if you want to play along at home, you can install the requirements file from the repo (psutil is probably the only new one) and [run these tests](https://github.com/ejhumphrey/pescador-wtf/blob/master/test_memleak.py) with pytest.

**Comment by cjacoby** [comment]
Yeah, I see what's going on. I will dig into those tests after work today. Nice catch 👍

**Comment by bmcfee** [comment]
I think #47 covers this -- can we close it?

**Comment by ejhumphrey** [comment]
I'd agree to that
