### ISSUE TITLE
Keras generator interface

### ISSUE THREAD

**Issue by bmcfee** [pescadores/pescador#56]
I've been using pescador with keras lately, and find myself writing some glue code to convert the pescador stream outputs (dict) into a keras-friendly format (tuple).

What do people think about adding a simple streamer method that selects out target entries from the dict? Something like the following:

```python
class Streamer:
    ...
    def tup(self, *items, **kwargs):
        for data in self.generate(**kwargs):
            yield (data[item] for item in items)
```
which you could then use as

```python
model.fit_generator(my_stream.tup('name_of_input_variable', 'name_of_output_variable'), ...)
```

**Comment by ejhumphrey** [comment]
I'd rather fix keras than break pescador 😄 

but srsly, that's fine / makes sense.

but even more srsly, tuples are a bad idea.

**Comment by bmcfee** [comment]
> but even more srsly, tuples are a bad idea.

been reading https://attrs.readthedocs.io/en/stable/why.html#tuples eh?

**Comment by ejhumphrey** [comment]
ha, no, I think it's just common sense ... but thanks for arming me with a reference that I can now wield at people.

**Comment by bmcfee** [comment]
anyway --
what should we call such a wrapper function?

**Comment by cjacoby** [comment]
I was actually going to make this proposal myself, for the same reason.

`Streamer.tuples()` is okay with me.

One possible solution: make it a subclass of `Streamer`, like
`class TupleStreamer(Streamer)`, which returns tuples instead of dicts.

Then, `Streamer.tuples()` would actually do:
```
def tuples(self, *items, **kwargs):
    return TupleStreamer(self, *items, **kwargs)
```

Not 100% sure about it, but I currently think that might be a cleaner way. Will continue to mull over it.

**Comment by bmcfee** [comment]
I think I prefer the original version, since any `Streamer` subclass would automatically inherit it as a wrapper over the `generate` method, so it would work seamlessly with mux, zmq, and buffer.

What's gained by having a separate class for tuple streams?

**Comment by cjacoby** [comment]
I see your point, and agree 100%. Nevermind on that.
