### ISSUE TITLE
Doc improvements for 1.0

### ISSUE THREAD

**Issue by cjacoby** [pescadores/pescador#58]
Some proposed updates to the docs. @bmcfee - I just want your opinions on these before I proceed on them.

- [ ] I don't think the "Simple Example" is a real example, since it doesn't actually use Pescador. I propose to merge the "Simple Example" and "Advanced Example", or at least move the `Streamer` component into the Simple example.
- [ ] Fix / fill out the API Reference (This could just be a bug on my machine in generating them.)
- [ ] Buffered streamers example
- [ ] ZMQ Example
    - [ ] Basic example
    - [ ] More realistic example
- [ ] Examples plugging pescador in with common ML/DL frameworks
    - [ ] sklearn-style APIs
    - [ ] Keras
    - [ ] (Lasagne/Theano, Tensorflow, ...)

**Comment by bmcfee** [comment]
Absolutely!  This would actually be a great thing to do for [docathon](https://bids.github.io/docathon/).  (Or independently, cause why not.)

**Comment by cjacoby** [comment]
Oh! There's even one at Berkeley! I don't think I can take that much time
off work, though. I think at least some of these are pretty important for
V1.0, though, so I'll try to work on them this weekend.

**Comment by bmcfee** [comment]
.. and point-by-point, I like all of that.

I suppose since TF is moving toward keras for its high-level interface, maybe we can skip that one.

Possibly a good way to present the examples, rather than directly in sphinx docs, is as a [sphinx-gallery](sphinx-gallery.readthedocs.io).  That way, the scripts are directly downloadable.

**Comment by cjacoby** [comment]
Ah neat! :+1:

**Comment by cjacoby** [comment]
I'm still having this problem. I spent a while messing with configuration to try and fix it, but no luck.

I'm going to try to spin up a VM later today and see if I get the same problem in Linux / a different environment.
