### ISSUE TITLE
Language conventions

### ISSUE THREAD

**Issue by ejhumphrey** [pescadores/pescador#75]
I'm curious what our current stance is on `batch` vs `item` vs `sample`. I've found a [few places](https://github.com/pescadores/pescador/blob/master/pescador/core.py#L126) in the docs that return / yield `batches` or have `max_batches`, though I think this use is sufficiently distinct from [the buffered version](https://github.com/pescadores/pescador/blob/master/pescador/buffered.py#L77). And, given the whole "minibatch" thing, I wonder what the most clear language might be here. 

Personally, I'd propose that a `sample` is a dict of data structures, and a `batch` is a dict of iterable containers where the _first dimension_ of each points to a sample. I think this is sufficiently general, and consistent with our [functional definition](https://github.com/pescadores/pescador/blob/master/pescador/buffered.py#L201).

**Comment by ejhumphrey** [comment]
Adding to this, I would also propose using `max_iter` where appropriate, in place of `max_{samples|batches}` ... which would signify agnosticism about what is being yielded.

**Comment by cjacoby** [comment]
:+1: both of these proposals.

In hindsight, I found that confusing /a problem whole writing the docs, but
was too engaged in the task to meta the thought.

I think in particular I would expect  "buffered streamers" to functionally
produce "minibatches", and... Well that leads to exactly all of what Eric
said in my head.

**Comment by ejhumphrey** [comment]
okay, I'll spin up a language linting branch now and sling around for y'alls review post-haste

**Comment by ejhumphrey** [comment]
merp, first bump in the road ... @cjacoby can I trouble you for some context around `buffered.__split_batches`? The overloaded nature of `batch` in this submodule is making it hard for me to grok, and there doesn't seem to be an explicit test for me to examine 🙀

**Comment by cjacoby** [comment]
Hokay, so, I *think* this is the correct context. I completely agree with
you that this is where "batch" gets problematic.

* `buffer_batch` produces *something* from it's streamer. You actually
don't know, I think, at this point if they are `batches` (Eric Version), or
`samples` (Eric Version), because upstream `Streamers` can produce either.
* __split_batches takes the stream generated before, and returns the right
number of *samples* for the `buffer_size` you had specified.

I think. I wasn't heavily involved in the original construction of this,
but I'm pretty sure that's what it does.

**Comment by cjacoby** [comment]
Further thoughts on your `sample`/`batch` distinction:

* do `Sample`s have no sample dimension, and that gets added by `Buffer`ing into `batch`es?
* If that's true, that's only necessarily a safe distinction if you provide some direct way to know that without asking about the `.shape` of the ndarray.

You can reasonably assume that an `ndarray` with shape `(n)`, is a `Sample` of dimension `n`. But you *can't* assume that with more ndimns. Is an `ndarray` with shape `(10, 10)` 10 Samples of Shape `(10,)`? I suppose you could figure this out if you had multiple keys in the Sample/Batch, by looking at the first dimension to see if they are the same, but what if you just have `{'X': ...}`?

Or perhaps I'm missing something about what you are proposing?

**Comment by ejhumphrey** [comment]
I think the only constraint is that `batch[key].ndim - 1 == sample[key].ndim`. This isn't directly helpful in addressing your questions, but ... I think the distinction we would have to make is between a `sample_stream` and a `batch_stream`, in that, maybe the generator has a class / type? e.g. `class Buffer(Streamer): ...`

I'm not sure yet. But! I think fixing it at the "what kind of generator are you" helps with the data model. Buffers could also be called Accumulators, Aggregators, or DelayLines ... and maybe it's the responsibility of the user / developer to keep an eye on the shape of their data. 

one final thought and then i'ma bike home. Perhaps the contract the API makes with the user is the following (note that not all of this is novel / different from what exists): 
- The core iterable type is a `Streamer`
- Streamers work for any generator / iterable type.
- There are two types of `Streamers` that we care about: Samplers and Buffers
- There is no `sample`, there is no `batch`: there is only `data`, a dict of `key: np.ndarray` pairs.
- Samplers produce `data` with the same `ndim`s of what it consumes. (I ... don't know if / how we enforce that, maybe with some kind of `input_shape` spec). 
- Buffers produce `data` with `ndim+1` of what it consumed.
- The user is responsible for tracking the semantics of what "data" represents

I ... think this is clean and makes sense?

**Comment by cjacoby** [comment]
I dig it. 👍  It is a minor, subtle change on the current structure, only in the clarity direction. 

(Now we just need @bmcfee to weigh in.)

**Comment by bmcfee** [comment]
> The core iterable type is a Streamer

:+1:

> Streamers work for any generator / iterable type.

:+1:

> There are two types of Streamers that we care about: Samplers and Buffers

What is a Sampler?

> There is no sample, there is no batch: there is only data, a dict of key: np.ndarray pairs.

:+1:

> Samplers produce data with the same ndims of what it consumes. (I ... don't know if / how we enforce that, maybe with some kind of input_shape spec).

I'm not sure what that means: what do samplers "consume"?

> Buffers produce data with ndim+1 of what it consumed.

That seems reasonable.  Additional contract: all elements going through a buffer must match shape in all dimensions.


> The user is responsible for tracking the semantics of what "data" represents

:+1:

**Comment by ejhumphrey** [comment]
**note:** I've updated my proposal above to have Roman numerals for ease of reference.

> What is a Sampler?

Having time to digest things further, I would strike the Sampler / Buffer distinction from all claims and remove (iii) outright. 

Two thoughts regarding the `BufferedStreamer` class: 
- I've been yet unable to understand what purpose this class serves.
- I think "buffering" as a concept is inherently a filter / transform operation, in contrast to a Streamer which is actually a "source". @bmcfee, your phrase "...going through a buffer..." acknowledges it. This point clarifies (v) in my head.

I have a revised set of points to follow up with shortly.

**Comment by ejhumphrey** [comment]
kay, post-lunch proposal (not committed to any of the names below):

**Streaming and Iteration**
[1.1] Any object that can be iterated, e.g. `for x in thing: ...`, is referred to as an "iterable", per [standard Python library syntax](https://docs.python.org/3/library/itertools.html#module-itertools). 
[1.2] This in contrast to an "iterator", defined here as a callable object that is / returns an iterable, e.g. `range`.
[1.3] A "stream" is defined as the sequence of objects yielded by an iterable.
[1.4] For (over) completeness, `range` is an iterator, `range(8)` is iterable, and the stream is (consecutively) `0, 1, 2, ...`
[2] Pescador defines an object (currently) called a `Streamer` to effectively decorate an iterator and its arguments, e.g. `Streamer(range, 8)` and not `Streamer(range(8))`. This is necessary for a Streamer to do its main job, "rebooting" an iterator for continuous iteration.
[3] A Streamer, true to the principles of a decorator, should transparently yield *whatever* its iterator does.

**Data Sampling**
[4] Pescador defines the design / interface of a type of iterator, referred to as a `Sampler`. A `Sampler` is defined as (a) taking zero or more arguments, (b) is iterable when instantiated, e.g. `for data in Sampler(): ...`, and (c) returns objects referred to as "data".
[5] A `data` object is a dict of `key: np.ndarray` pairs. As far as pescador is concerned, objects that do not meet this criteria are not "data".

**Transformers**
[6] Pescador defines a design / interface referred to as a `Transformer`. Transformer is defined as taking `data`-like objects as input and output, and preserves iteration, e.g. `for data in Transformer(Sampler()):...`.
[7] One common Transformer might be `buffer_stream`, which accumulates `data` into a FIFO queue, and yields one `data` object for every *N* in, grouping values by keys.

how we doin?

**Comment by ejhumphrey** [comment]
**note**: I've since realized that `range` isn't an iterator, so my e.g.'s, while simple, won't work.

**Comment by bmcfee** [comment]
For reference, the iterator/iterable/generator distinction is codified in `collections.abc` [here](https://docs.python.org/3/library/collections.abc.html#module-collections.abc) and the [glossary](https://docs.python.org/3/glossary.html#term-iterable) definition:

> iterable
> ---
> An object capable of returning its members one at a time. Examples of iterables include all sequence
> types (such as `list`, `str`, and `tuple`) and some non-sequence types like `dict`, `file` objects, 
> and objects of any classes you define with an `__iter__()` or `__getitem__()` method. Iterables can
> be used in a for loop and in many other places where a sequence is needed (`zip()`, `map()`, ...). 
> When an iterable object is passed as an argument to the built-in function `iter()`, it returns an 
> iterator for the object. This iterator is good for one pass over the set of values.


> This in contrast to an "iterator", defined here as a callable object that is / returns an iterable, e.g. range.

I don't think your definition of `iterator` is consistent with the python [terminology](https://docs.python.org/3/glossary.html#term-iterator).

I see no reason to not subclass `Streamer` from `Iterable`, and use `__iter__` as a wrapper for the current `__call__` with default parameters.



> [3] A Streamer, true to the principles of a decorator, should transparently yield whatever its iterator does.

I like this in principle, but it's awfully convenient to have `Buffer` inherit from `Streamer`.  Similarly, `Mux` doesn't fit this definition either, but it does otherwise behave like a streamer.



> [4] Pescador defines the design / interface of a type of iterator, referred to as a Sampler. A Sampler is defined as (a) taking zero or more arguments, (b) is iterable when instantiated, e.g. for data in Sampler(): ..., and (c) returns objects referred to as "data".

So a `Sampler` is just an abstraction for what we currently treat as the generator parameter in Streamer?    This seems maybe a little overwrought: are we expecting users to define data generators by inheriting from `pescador.Sampler`?  Or are you proposing a decorator that would wrap generators as `Sampler` objects automagically so that we can type-check them later?



> [5] A data object is a dict of key: np.ndarray pairs. As far as pescador is concerned, objects that do not meet this criteria are not "data".

:+1: but are you proposing to define this as a type?  Or otherwise try to check/enforce that samplers only produce `data`?  Dynamic checking is possible but slow, static checking seems nigh impossible.



> [6] Pescador defines a design / interface referred to as a Transformer. Transformer is defined as taking data-like objects as input and output, and preserves iteration, e.g. for data in Transformer(Sampler()):....

ITYM Transformer takes an iterator of data objects.  I see this for `Buffer` but it's not clear how one would fit `Mux` into this design.  I think it's reasonable to want both `Buffer` and `Mux` to exist at the same level of abstraction, since they're both in some sense meta-streamers.

**Comment by ejhumphrey** [comment]
rockin, will digest and form better, more informed ideas 👍

**Comment by ejhumphrey** [comment]
okay! first off, @bmcfee thanks for the pointers, I definitely feel like I've got a better grasp of standard terms / definitions now (but we'll see :o):

**A – Definitions**
(summarizing Python standards)
[A.1] An iterator is an object that produces a sequence of data, i.e. via `__next__` / `next()`.
[A.2] An iterable is an object that can produce iterators, i.e. via `__iter__` / `iter()`.
[A.3] A "stream" is the sequence of objects produced by an iterator.
[A.4] A "generator" (or more precisely "generator function") is a callable object that returns a single generator iterator.
[A.5] For example, `range` is a iterable function, `range(8)` is an iterable, and its iterator produces the stream (consecutively) `0, 1, 2, ...`

**B – Streaming data**
[B.1] Pescador defines an object called a `Streamer` for the purposes of (re)creating iterators indefinitely and (optionally) interrupting them prematurely.
[B.2] `Streamer` inherits from `iterable` and can be iterated directly.
[B.3] A `Streamer` can be initialized with one of two types:
[B.3.1] Any iterable type, e.g. `range(7)`, `['foo', 'bar']`, `"abcdef"`, or another `Streamer()`
[B.3.2] A generator function and its arguments + keyword arguments.
[B.4] A `Streamer` transparently yields the data stream flowing through it. 
[B.4.1] A `Streamer` should not modify objects in its stream.
[B.4.2] In the spirit of encapsulation, the modification of data streams is achieved through separate functionality (see Section D, below).

**C – Multiplexing data streams**
[C.1] Pescador defines an object called a `Mux` for the purposes of stochastically multiplexing streams of data.
[C.2] `Mux` inherits from `Streamer`, which makes it both iterable and recomposable, e.g. one can construct arbitrary trees of data streams.
[C.3] A `Mux` is initialized with a container of one or iterables, and parameters to control the stochastic behavior of the object.
[C.4] As a subclass of `Streamer`, a `Mux` also transparently yields the data stream flowing through it, i.e. [B.4].

**D – Processing data streams**
[D.1] Pescador adopts the concept of "transformers" for processing data streams.
[D.1.1] A transformer takes as input a single object in the stream.
[D.1.2] A transformer yields an object.
[D.1.3] Transformers are iterators, i.e. implement a `__next__` method, to preserve iteration.
[D.1.4] An example of a built-in transformer is `enumerate` [[ref](https://docs.python.org/3.3/library/functions.html#enumerate)].

*Commentary* 
- I want to pause on `data` and sampling for right now.
- I agree that Mux should be a subclass of Streamer; I don't understand why data stream agnosticism is incompatible with this.
- Having thought about it a bunch, I increasingly think `buffer_stream` could be more like `enumerate` or `zip` than `Streamer`. In other words, I think buffer is an `operation` (or iterable function), where Streamer / Mux are wires / routers / switches ... but that's circuit design taking over my brain.

**Comment by ejhumphrey** [comment]
Update for posterity:
[A.6] We use "streamer" to refer to the union of generator functions and iterables.

**Comment by ejhumphrey** [comment]
closed with #88
