### ISSUE TITLE
Refactoring tests?

### ISSUE THREAD

**Issue by ejhumphrey** [pescadores/pescador#78]
kay, last issue of the day before actually _doing_ something 😄 

I would like to indulge my OCD and refactor the tests directory to take a `{name}.py -> test_{name}.py` structure. By that paradigm, we're currently missing `test_core.py` and `test_buffered.py`... it's all getting tested, since our coverage is ≈97%, but I'm finding it less than obvious how / where to dive in and start making changes.

what say you @cjacoby @bmcfee?

**Comment by cjacoby** [comment]
I am not offended by this, go for it as far as I'm concerned.

I have two bonus thoughts about this (these are on principle, requiring no actual changes to your proposals... yet)
1. I agree in general about `{name}.py -> test_{name}.py`, with the following modifications:
    * Due to the py.test inability to handle multiple test files with the same name, I usually do:
      `{submodule}/{name}.py => test_{submodule}_{name}.py`
    although that doesn't matter to us yet. (But would on your transforms proposal)

2. To me Integration/system tests or the like also don't necessarily follow this convention.

**Comment by ejhumphrey** [comment]
closed with #88
