### ISSUE TITLE
Documentation Updates for 1.1

### ISSUE THREAD

**Issue by cjacoby** [pescadores/pescador#83]
- [x] Fix/update semantics to match the discussion / decisions in #75 
    - [x] samples vs batches
    - [x] iterators, iterables, and generators
- [x] BufferedStreamer => buffer_stream
- [x] buffer_batch => buffer_stream
- [x] New buffer_stream behavior (vstack, adding dimension)
- [x] Minor mux semantics changes
- [x] pescador.maps

**Comment by ejhumphrey** [comment]
We should also be sure to disambiguate what we mean by `bags`, `samples`, and `examples` (if we use the latter).

**Comment by ejhumphrey** [comment]
For clarity:
- An audio file would correspond to an `example`
- The act of drawing slices / windowed observations / what have you corresponds to a `sample`.
- A `bag` is a collection of `samples`. 

Note that one or more `bags` can be constructed over a single `example`, as in the case of "my audio file is 1 hour long, and needs to be segmented to fit into memory" in which case, these would need to be multiplexed into a single data stream.

**Comment by bmcfee** [comment]
What's left to do on this one?

**Comment by bmcfee** [comment]
Offline conversation with @cjacoby today: sounds like this is done, and I can begin drafting the 1.1 release.
