### ISSUE TITLE
Validators

### ISSUE THREAD

**Issue by ejhumphrey** [pescadores/pescador#92]
Drawing inspiration from experience + paddle's [data provider](http://www.paddlepaddle.org/doc/ui/data_provider/pydataprovider2.html?highlight=data%20provider#paddle.trainer.PyDataProvider2.provider), we can implement validation as a reusable map operation.

**Comment by bmcfee** [comment]
Pasting in my scratch example, here's a design that I kinda like.  It matches the callback interface i sketched out in #85: 

```python
class Validator(object):

    def __init__(self, **kwargs):
        self.fields = kwargs

    def __call__(self, streamer, strict=True):

        return Streamer(self.validate, self.fields, streamer, strict=strict)

    def validate(cls, fields, streamer, strict=True):

        for data in streamer:
            if data.keys() != fields.keys():
               raise ValidationError(...)
            for key in fields:
                # Check shape and dtype
                if strict:
                    raise ValidationError(...)
                else:
                    warn('Validation error...')
            yield data


v = Validator(x=((10,4), float), y=((10), int))

p = Streamer(my_streamer, filename)

for data in p:
    pass

for data in v(p):
    pass

for data in v(p, strict=False):
    pass
```

So `Validator` is an object that can construct streamers when applied to other streamers.

**Comment by bmcfee** [comment]
Any objection to bumping this to 2.1?

**Comment by cjacoby** [comment]
I think this shouldn't affect the current API at all, so that seems like a good plan to me.

**Comment by bmcfee** [comment]
Circling back on this: I wonder if it would make more sense to use [data classes](https://docs.python.org/3/library/dataclasses.html) here?  I'm thinking that if a dataclass is defined in advanced, and a streamer is supposed to generate data according to that format, then validation simplifies to a type-check on the iterate, and `validate` can just become a map:

```python
def validate(stream, dc):
    for x in stream:
        if isinstance(x, dc):
            yield x
        else:
            raise ...
```

Where this could get a little interesting is in other stream filters (tuples, buffer_stream, etc).  Dataclasses can convert to tuples and dicts easily, but buffering would have to know the data class to construct a new DC from the iterates.

Overall, I think this might be a good direction to go in general, and we should encourage data classes over dicts for streamer outputs whenever possible.

**Comment by cjacoby** [comment]
yes, though DataClasses are >=3.7

**Comment by bmcfee** [comment]
> yes, though DataClasses are >=3.7

Indeed.  the `validate` pattern above is really just a type-agnostic checker though, so it doesn't have to know what dc's are to work.  It could just as easily be `validate(stream, np.ndarray)` (though that's not so useful).  Maybe a more interesting validator pattern would be 

```python
def validate(stream, callable):
    for x in stream:
        if callable(x):
            yield x
        else:
            raise ...

data = validate(stream, lambda x: isinstance(x, my_favorite_type))
```

Then you could put any arbitrary checker logic into the callable without having to write the exception handling boilerplate.

**Comment by bmcfee** [comment]
Iterating on this one more time: I think this actually makes the most sense as a `filter` pattern with an optional `raise` flag.

```python
def filter(stream, callable, error=True):
    for x in stream:
        if callable(x):
             yield x
        elif error:
             raise PescadorError(f'Failed check: {callable}({x})')
```
This way, you can either error out (default) when a check fails, or simply remove it from the stream.  Both are reasonable actions depending on circumstances, and this pattern makes it easy to do both.

**Comment by bmcfee** [comment]
Thinking more on this, do we actually want to implement anything here?

You should be able to get the same overall behavior as follows:

```python
def cond(x):
    if not isinstance(x, MyType):
        raise TypeError
    return True

itertools.ifilter(cond, stream)  # Throw an exception when validation fails
itertools.ifilter(lambda x: isinstance(x, MyType), stream)  # Filter without throwing exceptions
```

I see no benefit to reimplementing itertools functionality here, as it will only be slower and more work to maintain.
