### ISSUE TITLE
Cache operations

### ISSUE THREAD

**Issue by ejhumphrey** [pescadores/pescador#93]
stochastic IIR filter for samples in a stream, providing sample reuse

**Comment by ejhumphrey** [comment]
changed my mind, this is a better 2.0 milestone, there's gonna be some thought that goes into this design

**Comment by bmcfee** [comment]
Had to unpack and explain this one today.  As I recall, here's what we actually had in mind:

`cache(stream, k, prob=0.5)`.  This maintains a cache of size `k` items.  With probability `prob`, it yields the next item from the stream and adds it to the cache (evicting the oldest item if `|cache|==k`).  With probability `1-prob` it yields a random item from the cache.

**Comment by bmcfee** [comment]
Since nothing within pescador depends on this, can we move it up to a 2.1 milestone?

**Comment by cjacoby** [comment]
👍

**Comment by bmcfee** [comment]
Here's a rough cut of the cache map
```python
from pescador import PescadorError

def cache(stream, k, prob=0.5, random_state=None):
    '''Stochastic cache of a stream.
    
    With probability `prob`: yield a new item from `stream` and place it in the cache
    
    With probability `1-prob`: yield a previously seen item from the cache
    
    When the cache exceeds size `k`, a previously seen item is selected at random for eviction.
    
    Parameters
    ----------
    stream : iterable
        The stream from which to sample
        
    k : int > 0
        The size of the cache
        
    prob : float in [0, 1)
        The probability with which to select a new item
        
    random_state : None, int, or np.random.RandomState
        If int, random_state is the seed used by the random number generator;

        If RandomState instance, random_state is the random number generator;

        If None, the random number generator is the RandomState instance
        used by np.random.

    Yields
    ------
    data
        elements of `stream`
    '''
    if random_state is None:
        rng = np.random
    elif isinstance(random_state, int):
        rng = np.random.RandomState(seed=random_state)
    elif isinstance(random_state, np.random.RandomState):
        rng = random_state
    else:
        raise PescadorError('Invalid random_state={}'.format(random_state))

    cache = []
    
    while True:
        if len(cache) < k or rng.rand() >= prob:
            # We don't have enough data yet; grab an item and yield it
            cache.append(next(stream))
            yield cache[-1]
        else:
            yield rng.choice(cache)
            
        if len(cache) > k:
            cache.pop(rng.randint(low=0, high=k))
```

**Comment by bmcfee** [comment]
Looking back over this, I think the comment above basically does everything we'd want?

The only other thing I can think of, relating to @ejhumphrey's original motivation here, is the ability to access the `cache` container directly.  This way you could always have access to a "batch" of data without having to iterate `k` times.  However, I don't see a clean way to do that without adding a lot of misdirection around data access to make sure that `next(stream)` is triggered when it needs to be.  I'm inclined to keep the simple cache implementation described above.

**Comment by bmcfee** [comment]
One hitch in the implementation above is that list.pop is O(k) for intermediate indices.  (See: [wiki on time complexity](https://wiki.python.org/moin/TimeComplexity).)

We can do this more efficiently at the cost of some elegance by picking an index first, then flipping a coin to decide whether or not to replace it before yielding.

**Comment by bmcfee** [comment]
One more question that popped up in testing: what should the finite stream behavior of cache be?

If the input stream produces `n` samples, then the cached version will produce some `n' >= n` that depends on `prob` (negative binomial strikes again).  Should we expect it to last forever once the input stream is consumed (by reusing the cache indefinitely), or just document the life-extension behavior and keep it simple?
