### ISSUE TITLE
Not all docstrings make it to the docs

### ISSUE THREAD

**Issue by rabitt** [pescadores/pescador#99]
The API reference in the [documentation](http://pescador.readthedocs.io/en/stable/api.html) is missing a bunch of information. The doc strings in the code are well written and complete but aren't getting parsed when the docs are built.

For example, the `Mux` class has a bunch of arguments in the init method that are documented well in the [doc string](http://pescador.readthedocs.io/en/stable/api.html#multiplexing) but in the docs only [the example](http://pescador.readthedocs.io/en/stable/api.html#multiplexing) and the components inhereted from the base class make it.

**Comment by cjacoby** [comment]
I think I see why this might be. Looking into it.

**Comment by cjacoby** [comment]
This should be fixed in #95.
